use_frameworks!

platform :ios, '8.0'

target 'SJWeChatOpenSDK_NoPay_Example' do
  pod 'SJWeChatOpenSDK_NoPay', :path => '../'

  target 'SJWeChatOpenSDK_NoPay_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
